package com.scamshield.analyzer.url

import com.google.common.truth.Truth.assertThat
import java.io.File
import org.junit.jupiter.api.Test

/**
 * The fixture `reputation_test_fixture.bin` was generated by actually running
 * `rulepack/build_rulepack.py`'s own bloom-building functions against a small fixed domain
 * set (see the generation script noted in DECISIONS.md), then querying the SAME Python data
 * structures for the expected true/false answer on every domain below.
 *
 * This is the test that would have caught the original bug in this class: an early version
 * computed `h1 + i * h2` in a plain `Long`, which silently overflows for i >= 1 given real
 * SHA-256 output, while Python's `%` operates on unbounded integers. That version passed
 * every test that only checked internal consistency; only checking against independently
 * Python-computed expectations exposed it.
 */
class BloomDomainReputationIndexTest {

    private val index = run {
        val bytes = locateFixture().readBytes()
        BloomDomainReputationIndex.parse(bytes) ?: error("fixture failed to parse")
    }

    private fun locateFixture(): File {
        var dir = File(".").absoluteFile
        repeat(6) {
            val candidate = File(dir, "analyzer/url/src/test/resources/reputation_test_fixture.bin")
            if (candidate.exists()) return candidate
            dir = dir.parentFile ?: error("could not locate reputation_test_fixture.bin")
        }
        error("could not locate reputation_test_fixture.bin")
    }

    @Test
    fun `every domain the python builder inserted reads as established`() {
        val positives = listOf(
            "google.com", "wikipedia.org", "sbi.co.in", "amazon.in", "microsoft.com",
            "github.com", "python.org", "openai.com", "reddit.com", "nytimes.com",
        )
        for (domain in positives) {
            assertThat(index.isEstablished(domain)).isTrue()
        }
    }

    @Test
    fun `domains confirmed non-established in python read the same way here`() {
        // Independently re-derived from the same Python bloom data before this test was
        // written -- these are not false positives against this specific small filter.
        val negatives = listOf(
            "totally-fake-scam-domain-xyz123.top",
            "sbi-kyc-verify.xyz",
            "not-a-real-bank-site.tk",
            "random-unlisted-site-99.info",
            "another-fake-one.click",
            "yet-another-scam.buzz",
        )
        for (domain in negatives) {
            assertThat(index.isEstablished(domain)).isFalse()
        }
    }

    @Test
    fun `established check is case-insensitive`() {
        assertThat(index.isEstablished("GOOGLE.COM")).isTrue()
        assertThat(index.isEstablished("Google.Com")).isTrue()
    }

    @Test
    fun `allowlist entries match exactly and case-insensitively`() {
        assertThat(index.isAllowlisted("onlinesbi.sbi")).isTrue()
        assertThat(index.isAllowlisted("sbicard.com")).isTrue()
        assertThat(index.isAllowlisted("ONLINESBI.SBI")).isTrue()
    }

    @Test
    fun `allowlist does not match a domain not in the pack, even if bloom-established`() {
        // google.com is established (in the bloom filter) but not in the small allowlist --
        // the two checks are independent, per the DomainReputationIndex interface contract.
        assertThat(index.isAllowlisted("google.com")).isFalse()
    }

    @Test
    fun `a corrupt or truncated byte array fails to parse rather than throwing`() {
        assertThat(BloomDomainReputationIndex.parse(byteArrayOf(1, 2, 3))).isNull()
        assertThat(BloomDomainReputationIndex.parse(ByteArray(0))).isNull()
    }

    @Test
    fun `wrong magic bytes fail to parse`() {
        val bytes = "NOTAREALPACK1234567890".toByteArray()
        assertThat(BloomDomainReputationIndex.parse(bytes)).isNull()
    }
}
